apiVersion: v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
  labels:
    app: techtrends
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: techtrends
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path:  {{ .Values.livenessProbe }}
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path:  {{ .Values.readinessProbe }}
            port: {{ .Values.containerPort }}
